Resolving GAMBLR.viz issues
morinlab/GAMBLR.viz pull request #29
Opened 2023-12-19 20:49 UTC by Kdreval

This PR resolves some of the issues reported in GAMBLR.viz:

- #28

2023-12-19 23:46 UTC, Kdreval commented
@mattssca @vladimirsouza this is ready for review. Some issues related to the `prettyOncoplot` and `prettyCoOncoplot`

2023-12-20 18:41 UTC, mattssca requested changes
Thanks, Kostia. nice to get rid of the maftools pacakge. One less dependency to worry about. For the most part, the changes in this PR look good, I only had a few comments. I can also wait with the approval of this PR if you want to add fix for issue #16. Let me know how you want to proceed. I've also attached the figures I generated running the examples.

2023-12-20 18:41 UTC, mattssca commented on R/prettyCoOncoplot.R
>  #' meta = GAMBLR.data::gambl_metadata
Perhaps it would look nicer if we get the metadata using the GAMBLR function created for this, i.e. not just load the bundled `.Rda` object?

2023-12-20 18:41 UTC, mattssca commented on R/prettyOncoplot.R
> +#' gene_groups = c(rep("FL", length(bl_genes)), rep("DLBCL", length(dlbcl_genes)))
I think there's a small typo in this line of the example. I assume you want to refer to the `fl_genes` object and not the `bl_genes`;

```
> gene_groups = c(rep("FL", length(bl_genes)), rep("DLBCL", length(dlbcl_genes)))
Error: object 'bl_genes' not found
```

2023-12-20 18:41 UTC, mattssca commented on R/prettyOncoplot.R
> +#' gene_groups = c(rep("FL", length(bl_genes)), rep("DLBCL", length(dlbcl_genes)))
![prettyonco](https://github.com/morinlab/GAMBLR.viz/assets/32147626/3247bd7c-4809-4aba-a38a-c384eda40449)

2023-12-20 18:41 UTC, mattssca commented on R/prettyCoOncoplot.R
>  #' meta = GAMBLR.data::gambl_metadata
![coonco](https://github.com/morinlab/GAMBLR.viz/assets/32147626/d499c7de-6867-4247-b79d-b21f63d09a08)

2023-12-20 19:27 UTC, Kdreval commented
Thanks Adam! I fixed those typos and leftovers from previous examples, definitely better to use the designated function!
Re: the issue 16, Krysta will work on this because she already had some updates to that function so that will be a separate PR

2023-12-20 22:12 UTC, mattssca approved these changes

2023-12-20 22:12 UTC, mattssca commented
Thanks, Kostia. This PR is now approved and ready for merge!

2023-12-20 22:14 UTC, merged

2023-12-20 22:14 UTC, Kdreval commented
Nice! Just on time for addressing the issue 16!