mirrored_lollipop_plot.R
morinlab/GAMBLR.viz pull request #67
Opened 2024-09-03 21:11 UTC by Atlantis-Real

mirrored lollipop plot a comparison function for when studying/comparing 2 different cohorts, pathologies, etc.

2024-11-29 17:31 UTC, Kdreval commented
Thanks Luke @Atlantis-Real !
Looks like it needs some documentation update:
```
prettyForestPlot
  Code: function(maf, mutmat, metadata, genes, keepGeneOrder = FALSE,
                 min_mutations = 1, comparison_column, rm_na_samples =
                 FALSE, comparison_values = FALSE, separate_hotspots =
                 FALSE, comparison_name = FALSE, custom_colours =
                 FALSE, custom_labels = FALSE, max_q = 1)
  Docs: function(maf, mutmat, metadata, genes, keepGeneOrder = FALSE,
                 min_mutations = 1, comparison_column, rm_na_samples =
                 FALSE, comparison_values = FALSE, separate_hotspots =
                 FALSE, comparison_name = FALSE, custom_colours =
                 FALSE, custom_labels = FALSE, max_q = 1, mirrorarg =
                 FALSE)
  Argument names in docs not in code:
    mirrorarg
```
Can you please take care of this?

2024-12-06 17:09 UTC, Kdreval commented
@Atlantis-Real Let me know if you need any help with this :smile:

2024-12-13 16:58 UTC, lkhilton requested changes
I'm very pleased to see this in the works! I've added some suggestions based on my recent experience with this function.

2024-12-13 16:58 UTC, lkhilton commented on R/pretty_lollipop_plot.R
> +                    label = paste0(
I was going to remove this feature from the version I have been working on. I don't think it's wise to calculate the % mutated from the maf file - mafs are frequently subset by gene and/or patient ID and the maf probably doesn't represent the true denominator in many cases.

2024-12-13 16:58 UTC, lkhilton commented on R/pretty_lollipop_plot.R
>              data = domain_data,
I think that the protein model should be a separate plot from the lollipops, and then they should be arranged together. When you have a maf file that has many mutations (it's not uncommon to get > 20-30 mutations in a sample) the protein model gets really compressed. See for example this [Slack message](https://morinlabsfu.slack.com/archives/C06GR6YN7AA/p1734108232187889?thread_ts=1734107400.345649&cid=C06GR6YN7AA).

2025-01-15 22:18 UTC, Kdreval approved these changes

2025-01-15 22:18 UTC, Kdreval commented
Thanks @Atlantis-Real !

2025-01-15 22:18 UTC, Kdreval commented
@lkhilton can you please see if your changes are addressed? It doesn't let me merge without your approval 😄

2025-01-21 22:52 UTC, lkhilton requested changes

2025-01-21 22:52 UTC, lkhilton commented on R/pretty_lollipop_plot.R
> +    maf_df <- separate(
For this to work, the maf_df provided has to include the RefSeq column. It's not returned when you run `get_ssm_by_samples()` with default options, you have to specify `basic_columns = FALSE`. Could you include a check to make sure that the maf has this column, and return an informative error message if it's missing? 

I think unfortunately that also means this option won't be compatible with the maf that's returned by `GAMBLR.data`, which is another reason to give an informative error message.

2025-01-21 22:52 UTC, lkhilton commented on R/pretty_lollipop_plot.R
> +        gg_co_legend <- as_ggplot(get_legend(co_legend_data))
This errors as it is currently, I think it needs to specify `ggpubr::get_legend`

2025-01-21 22:52 UTC, lkhilton commented on R/pretty_colollipop_plot.R
> +    if (forestarg == TRUE) {
There are some issues with the final layout being quite compressed with overlapping text, even when printing to a plot that is 10" wide by 15" high. Also prettyForestPlot uses theme_Morons (arial font) while the rest of the plot uses the default Helvetica - perhaps best to change the theme for the forest_plot to match so the font is consistent.

2025-02-14 01:07 UTC, Atlantis-Real commented on R/pretty_lollipop_plot.R
> +    maf_df <- separate(
for sure! I have now added:

```
    if (!"RefSeq" %in% colnames(maf_df)) {
        stop("Error: The provided maf_df is missing the 'RefSeq' column. 
              Ensure that get_ssm_by_samples() is run with basic_columns = FALSE.")
    }
```

2025-02-14 01:31 UTC, Atlantis-Real commented on R/pretty_lollipop_plot.R
> +                    label = paste0(
Yep! heres the quick fix:

Somatic_Mutation_Denominator <- length(unique(metadata$Tumor_Sample_Barcode))

2025-03-05 23:20 UTC, Atlantis-Real commented
Sorry Laura! completely forgot to comment this! Ive made edits to both the lollipop and colollipop plot;

Ive made changes updating the these_samples_metadata
3caf446eeee413c640e44eec6daae77113a0e22e
b7bf45fbfaf68b3d8330dd2d9471ca62062a0654

I have also fixed the label issue with the coplot setting it to the default ggplot 11pt font size (though it is customizable) 
94d88181de1a70bcece3ce58411342b3eff0ba38


1) pretty_lollipop_plot() these_samples_metadata update:
# get meta data (BL_Thomas)
metadata <- get_gambl_metadata() %>%
    filter(cohort == "BL_Thomas") 
maf_df <- get_coding_ssm(
    these_samples_metadata = metadata
)
lolipop_result <- pretty_lollipop_plot(maf_df, these_samples_metadata = metadata, "CREBBP")
print(lolipop_result)


2) pretty_colollipop_plot() these_samples_metadata update (default font 11pt):
meta = GAMBLR.open::get_gambl_metadata()
metadata = dplyr::filter(meta, cohort %in% "BL_Thomas")
maf_df = GAMBLR.open::get_coding_ssm(
  these_samples_metadata = metadata
)
pretty_colollipop_plot_result <- pretty_colollipop_plot(maf_df = maf_df,
                                                        these_samples_metadata = metadata,
                                                        comparison_column = "sex",
                                                        comparison_values = c("M", "F"),
                                                        gene = "CREBBP",
                                                        label_threshold = 3,
                                                        forestarg = TRUE)
print(pretty_colollipop_plot_result)
![coplot_default_font](https://github.com/user-attachments/assets/02bbde25-caa1-418e-a052-bedcbed3ab2a)


3) pretty_colollipop_plot() (custom font 30pt):
meta = GAMBLR.open::get_gambl_metadata()
metadata = dplyr::filter(meta, cohort %in% "BL_Thomas")
maf_df = GAMBLR.open::get_coding_ssm(
  these_samples_metadata = metadata
)
pretty_colollipop_plot_result <- pretty_colollipop_plot(maf_df = maf_df,
                                                        these_samples_metadata = metadata,
                                                        comparison_column = "sex",
                                                        comparison_values = c("M", "F"),
                                                        gene = "CREBBP",
                                                        label_threshold = 3,
                                                        forestarg = TRUE,
                                                        font = 30)
print(pretty_colollipop_plot_result)
![font 30](https://github.com/user-attachments/assets/d606d838-1379-4fd9-9b4a-2011193dc498)

2025-05-02 16:39 UTC, rdmorin commented on R/pretty_lollipop_plot.R
>              data = domain_data,
I made some changes to this function that attempts to scale the size of the mutations and height of the protein domain consistently. I'm not 100% sure I made it better. Have you tried the latest version>

2025-05-02 16:41 UTC, rdmorin commented
@Atlantis-Real  can you please try to resolve the conflicts with the changes I added to pretty_lollipop_plot?

2025-07-07 20:54 UTC, lkhilton commented on R/pretty_lollipop_plot.R
> +        warning("The provided maf_df has more than one gene model for the specified gene.
Was this in reference to the warning about >1 RefSeq ID? If yes I think this is resolved now.

2025-07-07 21:09 UTC, lkhilton commented on R/pretty_lollipop_plot.R
> +#' lolipop_result <- pretty_lollipop_plot(maf_df, these_samples_metadata = metadata, "DDX3X")
Done.

2025-07-07 21:09 UTC, lkhilton commented on R/pretty_lollipop_plot.R
>  #' #get meta data (BL_Thomas)
Done.

2025-07-07 21:14 UTC, lkhilton commented on R/pretty_colollipop_plot.R
> +#'
Fixed.

2025-07-08 20:02 UTC, rdmorin approved these changes
I updated the docs with another example and regenerated the documentation pages. I think this is good to go now but @lkhilton may also have to approve it.

2025-07-08 20:31 UTC, lkhilton approved these changes

2025-07-08 20:31 UTC, lkhilton commented on R/pretty_colollipop_plot.R
> +        domain_data$p.value <- NA
<img width="879" alt="image" src="https://github.com/user-attachments/assets/b9711da8-f32e-478e-83ee-f249250e365c" />

2025-07-08 20:31 UTC, merged